Repository nuxt-modules/i18n, pull requests merged in 2022-09, with the labels that each got.

#1514 docs: fix typo in setup.md
  docs/content/20.getting-started/1.setup.md
Labels: doc

#1516 [next] fix(module): transpile edge aswell
  src/module.ts
Labels: bug 🐛, next

#1522 fix: improve error handling for vue-i18n v9 invalid message syntax
  package.json
  yarn.lock
Labels: next

#1523 fix: avoid deprecated use of `params` on vue-router
  package.json
  src/alias.ts
  yarn.lock
Labels: next
