Repository nuxt-modules/i18n, pull requests merged in 2023-03, with the labels that each got.

#1902 fix: defineI18nRoute do not work client-side
  src/runtime/utils.ts
Labels: bug 🐛

#1931 docs: mention callbacks
  docs/content/2.guide/2.runtime-hooks.md
Labels: doc, v8

#1955 feat: add basic module locale merging
  docs/content/2.guide/13.extend-messages.md
  docs/content/4.API/5.nuxt.md
  playground/layer-module/index.ts
  playground/layer-module/locales/en.json
  playground/layer-module/locales/fr.json
  playground/layer-module/locales/nl.json
  playground/layer-module/nuxt.config.ts
  playground/nuxt.config.ts
  specs/fixtures/basic_layer/layer-module/index.ts
  specs/fixtures/basic_layer/layer-module/locales/en.json
  specs/fixtures/basic_layer/layer-module/locales/fr.json
  specs/fixtures/basic_layer/layer-module/locales/nl.json
  specs/fixtures/basic_layer/layer-module/nuxt.config.ts
  specs/fixtures/basic_layer/nuxt.config.ts
  specs/fixtures/basic_layer/pages/index.vue
  specs/register_module.spec.ts
  src/bundler.ts
  src/layers.ts
  src/module.ts
  src/types.ts
  src/utils.ts
Labels: WIP, v8
