Repository nuxt-modules/i18n, pull requests merged in 2024-09, with the labels that each got.

#3087 fix: cookie being reset on reload in ssg build
  specs/ssg/no_prefix.spec.ts
  specs/utils/context.ts
  specs/utils/nuxt.ts
  specs/utils/server.ts
  src/runtime/plugins/i18n.ts
Labels: cr-tracked

#3088 fix: set default values for `locales` and `restructureDir`
  src/constants.ts
Labels: cr-tracked

#3093 fix: empty `i18n` options not loading `vue-i18n` config file
  pnpm-lock.yaml
  specs/empty_options.spec.ts
  specs/fixtures/empty_options/app.vue
  specs/fixtures/empty_options/i18n.config.ts
  specs/fixtures/empty_options/nuxt.config.ts
  specs/fixtures/empty_options/package.json
  specs/fixtures/empty_options/tsconfig.json
  src/layers.ts
  src/module.ts
  src/nitro.ts
Labels: regression

#3096 refactor!: rename public runtime config properties
  docs/content/docs/5.v9/2.guide/19.breaking-changes-in-v9.md
  docs/content/docs/5.v9/3.options/9.runtime-config.md
  specs/different_domains/different_domains.spec.ts
  src/module.ts
  src/runtime/internal.ts
  src/runtime/plugins/i18n.ts
  src/runtime/utils.ts
Labels: v9

#3098 fix!: nuxt context injected function types
  docs/content/docs/5.v9/2.guide/19.breaking-changes-in-v9.md
  playground/pages/[...catch].vue
  playground/pages/about/index.vue
  playground/pages/category/[id].vue
  specs/fixtures/basic/pages/blog/index.vue
  specs/fixtures/basic/pages/define-i18n-route-false.vue
  specs/fixtures/different_domains/pages/blog/index.vue
  specs/fixtures/multi_domains_locales/pages/blog/index.vue
  src/runtime/injections.ts
  src/runtime/plugins/i18n.ts
  src/runtime/routing/extends/i18n.ts
Labels: typescript, v9

#3103 chore: use `tinyexec` to run tests
  package.json
  pnpm-lock.yaml
  specs/utils/server.ts
  specs/utils/types.ts
Labels: test, deps

#2801 chore!: remove deprecated legacy dynamic route params
  docs/content/docs/5.v9/2.guide/19.breaking-changes-in-v9.md
  docs/content/docs/5.v9/2.guide/8.lang-switcher.md
  docs/content/docs/5.v9/3.options/2.routing.md
  playground/pages/[...catch].vue
  playground/pages/category/[id].vue
  src/bundler.ts
  src/constants.ts
  src/gen.ts
  src/module.ts
  src/runtime/composables/index.ts
  src/transform/meta-deprecation.ts
  src/types.ts
Labels: v9

#3100 refactor!: change `useLocaleHead` options shape and defaults
  docs/content/docs/5.v9/2.guide/19.breaking-changes-in-v9.md
  docs/content/docs/5.v9/2.guide/6.seo.md
  docs/content/docs/5.v9/4.api/1.index.md
  docs/content/docs/5.v9/4.api/5.vue.md
  specs/fixtures/basic/pages/index.vue
  specs/fixtures/basic_usage/layouts/default.vue
  specs/fixtures/basic_usage/pages/composables.vue
  specs/fixtures/basic_usage/pages/index.vue
  specs/fixtures/basic_usage/pages/nuxt-context-extension.vue
  specs/fixtures/different_domains/pages/index.vue
  specs/fixtures/inline_options/pages/index.vue
  specs/fixtures/issues/2590/app.vue
  specs/fixtures/lazy/pages/index.vue
  specs/fixtures/multi_domains_locales/pages/index.vue
  specs/fixtures/restructure/pages/index.vue
  src/runtime/composables/index.ts
  src/runtime/routing/compatibles/head.ts
  src/types.ts
Labels: v9

#3112 fix: use generated tsconfig and virtual file augmentations
  .github/workflows/ci.yml
  .nuxtrc
  eslint.config.js
  internals.d.ts
  package.json
  specs/basic_usage_compat_4.spec.ts
  src/logger.d.ts
  src/module.ts
  src/options.d.ts
  src/runtime/composables/index.ts
  src/runtime/composables/server.ts
  src/runtime/internal.ts
  src/runtime/plugins/i18n.ts
  src/runtime/routing/compatibles/head.ts
  src/runtime/routing/compatibles/routing.ts
  src/runtime/routing/compatibles/utils.ts
  src/runtime/routing/utils.ts
  src/runtime/utils.ts
  src/server.d.ts
  test/gen.test.ts
  test/pages/custom_route.test.ts
  test/utils.test.ts
  tsconfig.json
  tsconfig.test.json
Labels: cr-tracked

#3118 feat!: move to ESM only
  internals.d.ts
  package.json
Labels: cr-tracked

#3125 chore(deps): update intlify dependencies
  package.json
  pnpm-lock.yaml
Labels: cr-tracked

#3137 fix: update intlify dependencies
  .github/workflows/nightly-release.yml
  package.json
  pnpm-lock.yaml
Labels: cr-tracked

#3140 docs: styling tweaks and performance optimizations
  docs/app.config.ts
  docs/components/OgImage/DocsV9.vue
  docs/components/VersionSelect.vue
  docs/composables/usePageMeta.ts
  docs/layouts/docs.vue
  docs/nuxt.config.ts
  docs/package.json
  pnpm-lock.yaml
Labels: docs

#3142 feat: experimental typed routes
  build.config.ts
  docs/content/docs/5.v9/3.options/10.misc.md
  docs/content/docs/5.v9/4.api/3.compiler-macros.md
  package.json
  playground/nuxt.config.ts
  playground/pages/index.vue
  pnpm-lock.yaml
  specs/experimental/typed_pages.spec.ts
  specs/experimental/typed_pages_explicit_disable.spec.ts
  src/constants.ts
  src/gen.ts
  src/module.ts
  src/pages.ts
  src/runtime/components/NuxtLinkLocale.ts
  src/runtime/composables/index.ts
  src/runtime/shared-types.ts
Labels: cr-tracked

#3145 fix: warn when using SEO features without `baseUrl`
  src/runtime/composables/index.ts
  src/runtime/routing/compatibles/head.ts
Labels: cr-tracked
